// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjSbxCeoZjAlHzGcX8eSjk3ql9OUIaJYs',
    appId: '1:838853432656:android:350d5cf93077a88a6f4855',
    messagingSenderId: '838853432656',
    projectId: 'cusit-info',
    storageBucket: 'cusit-info.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6RFdBxJx9QsOfBa7qc5__k7R_J4EwVj4',
    appId: '1:838853432656:ios:1110b24196b9950e6f4855',
    messagingSenderId: '838853432656',
    projectId: 'cusit-info',
    storageBucket: 'cusit-info.appspot.com',
    iosBundleId: 'com.cusit.cusitinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6RFdBxJx9QsOfBa7qc5__k7R_J4EwVj4',
    appId: '1:838853432656:ios:6c1c794ac657eb296f4855',
    messagingSenderId: '838853432656',
    projectId: 'cusit-info',
    storageBucket: 'cusit-info.appspot.com',
    iosBundleId: 'com.cusit.cusitinfo.RunnerTests',
  );
}
